# Generated by Django 4.2.25 on 2025-10-31 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='final_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
