# Generated by Django 4.2.25 on 2025-10-31 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_enrollment_final_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='final_score',
        ),
    ]
